export const dashboardScreenStrings = {
  githubCom: 'Github.com',
  facebook: 'Facebook',
  googleOrganic: 'Google (organic)',
  vimeoCom: 'Vimeo.com',
  indiehackersCom: 'Indiehackers.com',
  havingDifficultiesUsingTheProduct: 'Having difficulties using the product',
  missingFeaturesINeed: 'Missing features I need',
  notSatisfiedAboutTheQualityOfTheProduct:
    'Not satisfied about the quality of the product',
  theProductDoesnTLookAsAdvertised: "The product doesn't look as advertised",
  other: 'Other',
  value17k: '$1.7K',
  direct: ' Direct',
  value24k: '$2.4K',
  indirect: ' Indirect',
  unitedStates: 'United States',
  italy: 'Italy',
  source: 'Source',
  visitors: 'Visitors',
  revenue: 'Revenue',
  sales: 'Sales',
  conversion: 'Conversion',
  breakdown: 'Breakdown',
  reasonForRefunds: 'Reason for refunds',
  text: '%',
  overview: 'Overview',
  dashboard: 'Dashboard',
  openShowcase: 'Open showcase',
  reviewYourWorkspaceActivityBrowseRecordsAndManageIncoming:
    'Review your workspace activity, browse records, and manage incoming requests.',
  loadingWorkspaceData: 'Loading workspace data…',
  workspaceDataUnavailable: 'Workspace data unavailable',
  pleaseTryLoadingYourWorkspaceAgain:
    'Please try loading your workspace again.',
  newInRange: (count: number) => `${count} new in range`,
  density: 'Density',
  modelExplorer: 'Model explorer',
  chooseHowMuchSpaceToUseForEachRecord:
    'Choose how much space to use for each record.',
  comfortable: 'Comfortable',
  compact: 'Compact',
  selectedModel: 'Selected model',
  visibleRecordsInTheCurrentQuery: ' visible records in the current query.',
  sampleAnalyticsDemoData: 'Sample analytics · demo data',
  directVsIndirect: 'Direct VS Indirect',
  orderValue: 'Order value',
  avgOrderValue: 'AVG Order Value',
  current: 'Current',
  previous: 'Previous',
  audience: 'Audience',
  topCountries: 'Top Countries',
  acquisition: 'Acquisition',
  topChannels: 'Top Channels',
  stores: 'Stores',
  salesOverTime: 'Sales Over Time',
  forecast: 'Forecast',
  finance: 'Finance',
  salesVsRefunds: 'Sales VS Refunds',
  records: 'Records',
  primaryDataTable: 'Primary data table',
  rows: ' rows',
  noRecordsAvailable: 'No records available.',
  registry: 'Registry',
  registeredModels: 'Registered models',
  recordsAvailableForOperationalViews:
    'Records available for operational views.',
  dec20: 'Dec 20',
  jan21: 'Jan 21',
  feb21: 'Feb 21',
  mar21: 'Mar 21',
  apr21: 'Apr 21',
  may21: 'May 21',
  value24k2: '2.4K',
  value3877: '$3,877',
  value267: '267',
  value47: '4.7%',
  value22k: '2.2K',
  value3426: '$3,426',
  value249: '249',
  value44: '4.4%',
  value20k: '2.0K',
  value2444: '$2,444',
  value224: '224',
  value42: '4.2%',
  value19k: '1.9K',
  value2236: '$2,236',
  value220: '220',
  value17k2: '1.7K',
  value2034: '$2,034',
  value204: '204',
  value39: '3.9%',
  value17k3: '$1.7K',
  value72: '$72',
  value34: '+34%',
  value1482: '1,482',
  value22: '-22%',
  value6796: '+$6,796',
  value342: '-34%',
} as const;
