export const labels = {
  accents: {
    aqua: 'Aqua',
    blue: 'Blue',
    indigo: 'Indigo',
    mint: 'Mint',
    salmon: 'Salmon',
    violet: 'Violet',
    amber: 'Amber',
    teal: 'Teal',
    rose: 'Rose',
    sky: 'Sky',
    emerald: 'Emerald',
    seafoam: 'Seafoam',
    coral: 'Coral',
    sunset: 'Sunset',
    orchid: 'Orchid',
  },
  tones: {
    neutral: 'Notice',
    info: 'Information',
    success: 'Success',
    warning: 'Warning',
    danger: 'Delete',
  },
  sides: {
    left: 'Left panel',
    right: 'Right panel',
    top: 'Top panel',
    bottom: 'Bottom panel',
  },
} as const;
