export const platformStrings = {
  common: {
    loading: 'Loading…',
    saving: 'Saving…',
    pendingValue: '…',
  },
  app: {
    backToWorkspace: 'Back to workspace',
    name: 'Portal',
    description: 'Your workspace for people, requests, and conversations.',
  },
  errors: {
    invalidInput: 'Check your entries and try again.',
    requestFailed: 'The request could not be completed. Try again.',
    unavailable: 'The service is temporarily unavailable. Try again shortly.',
    forbidden: 'You do not have permission to perform this action.',
    sessionExpired: 'Your session has expired. Sign in again.',
    notFound: 'This item could not be found.',
    untrusted: 'This request did not originate from Portal.',
    invalidPath: 'Invalid API path.',
    configuration: 'Portal is not configured for this service.',
    unexpected: 'Something went wrong. Please try again.',
    provider: 'This component must be rendered inside its provider.',
  },
  auth: {
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    invalidCredentials: 'The email or password is incorrect.',
    emailExists: 'An account already exists with this email.',
    invalidEmail: 'Enter a valid email address.',
    password: 'Use at least eight characters for your password.',
    name: 'Enter your name.',
    disabled: 'This account is disabled. Contact your administrator.',
    tooMany: 'Too many attempts. Please wait before trying again.',
    failed: 'Unable to sign in. Please try again.',
    signupFailed: 'Unable to create your account. Please try again.',
    sessionTooLarge: 'Unable to save this session. Contact your administrator.',
    loggedOut: 'Signed out',
    logoutFailed: 'Unable to sign out. Please try again.',
  },
  privacy: {
    title: 'Analytics preferences',
    description:
      'Essential cookies keep you signed in. Optional Amplitude analytics helps us understand which screens are useful. It stays off until you accept.',
    accept: 'Accept analytics',
    decline: 'Essential only',
    saved: 'Your analytics preference has been saved.',
    settings: 'Analytics preferences',
    demo: 'Analytics is disabled in this demo.',
  },
  notifications: {
    title: 'Browser notifications',
    enable: 'Enable notifications',
    disable: 'Disable notifications',
    enabled: 'Notifications enabled',
    available: 'Receive chat and workspace alerts in this browser.',
    denied:
      'Notifications are blocked. Change this site’s permission in your browser settings to enable them.',
    unsupported: 'Browser notifications are unavailable on this device.',
    demo: 'Notifications are simulated in demo mode.',
    unconfigured:
      'Browser notifications are not configured for this workspace.',
    failed: 'Could not update notifications. Please try again.',
    busy: 'Updating notifications…',
    alert: 'Workspace alert',
    disabled: 'Notifications disabled',
  },
  chat: {
    title: 'Chat',
    description: 'A shared workspace conversation.',
    placeholder: 'Write a message…',
    send: 'Send message',
    sending: 'Sending…',
    empty: 'No messages yet. Start the conversation.',
    failed: 'Your message was not sent. Please try again.',
    demo: 'Demo conversation',
    connected: 'Connected',
    connecting: 'Connecting…',
    offline: 'Live updates unavailable',
    simulate: 'Simulate alert',
    simulatedTitle: 'Demo alert',
    simulatedBody: 'Your workspace is up to date.',
    author: 'Portal team',
    seed: 'Welcome to Portal. Use this conversation to try out chat.',
  },
  environment: {
    missing: (name: string) => `Missing required environment variable: ${name}`,
    secret: 'SESSION_SECRET must contain at least 32 characters in live mode.',
    invalid: 'Invalid Portal environment configuration.',
  },
} as const;
