import { defineTheme } from '@astryxdesign/core/theme'
import { neutralTheme } from '@astryxdesign/theme-neutral'

export const portalTheme = defineTheme({
  name: 'portal',
  extends: neutralTheme,
  color: {
    accent: '#6D5EF8',
    neutralStyle: 'cool',
    contrast: 'high',
  },
  typography: {
    scale: {
      base: 15,
      ratio: 1.2,
    },
    body: {
      family: 'var(--font-geist-sans)',
      fallbacks: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      weight: 'normal',
    },
    heading: {
      family: 'var(--font-geist-sans)',
      fallbacks: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      weight: 'semibold',
      weights: {
        1: 'bold',
        2: 'bold',
        3: 'semibold',
      },
    },
    code: {
      family: 'var(--font-geist-mono)',
      fallbacks: '"SFMono-Regular", Consolas, monospace',
    },
  },
  radius: {
    base: 6,
    multiplier: 1.35,
  },
  motion: {
    fast: 120,
    medium: 280,
    slow: 680,
    ratio: 0.75,
  },
  tokens: {
    '--color-syntax-keyword': 'light-dark(#8B1A9E, #E9A8FF)',
    '--color-syntax-string': 'light-dark(#0E7A4F, #7FE0B4)',
    '--color-syntax-comment': 'light-dark(#7A8699, #6E7E96)',
    '--color-syntax-number': 'light-dark(#B45309, #FFB37F)',
    '--color-syntax-function': 'light-dark(#1D4FD8, #A0CAFF)',
    '--color-syntax-type': 'light-dark(#8B1A9E, #E9A8FF)',
    '--color-syntax-variable': 'light-dark(#0C1B33, #E5E9F0)',
    '--color-syntax-operator': 'light-dark(#7A8699, #9FB0C8)',
    '--color-syntax-constant': 'light-dark(#B45309, #FFB37F)',
    '--color-syntax-tag': 'light-dark(#C0243C, #FFAEAA)',
    '--color-syntax-attribute': 'light-dark(#9A6B00, #EEC12F)',
    '--color-syntax-property': 'light-dark(#0E7A6B, #83DAC9)',
    '--color-syntax-punctuation': 'light-dark(#98A5B8, #4E5E76)',
    '--color-syntax-background': 'light-dark(#F8F8F8, #070D18)',
    '--color-background-surface': 'light-dark(#FFFFFF, #111C2E)',
    '--color-background-body': 'light-dark(#F8F8F8, #0A1220)',
    '--color-background-card': 'light-dark(#FFFFFF, #16233A)',
    '--color-background-popover': 'light-dark(#FFFFFF, #1B2B45)',
    '--color-background-muted': 'light-dark(#F3F3F3, #1D2E49)',
    '--color-accent': 'light-dark(#6557E8, #A79CFF)',
    '--color-accent-muted': 'light-dark(rgba(101, 87, 232, 0.12), rgba(167, 156, 255, 0.16))',
    '--color-neutral': 'light-dark(#0C10130F, #DDE4E033)',
    '--color-overlay': 'light-dark(#0C101399, #050A14B3)',
    '--color-overlay-hover': 'light-dark(#0C10130D, #FFFFFF0D)',
    '--color-overlay-pressed': 'light-dark(#0C10131A, #FFFFFF1A)',
    '--color-text-primary': 'light-dark(#0C1013, #F5F8FD)',
    '--color-text-secondary': 'light-dark(#626668, #9FB0C8)',
    '--color-text-disabled': 'light-dark(#9A9EA0, #62728C)',
    '--color-text-accent': 'var(--color-accent)',
    '--color-on-dark': '#FFFFFF',
    '--color-on-light': '#0C1013',
    '--color-on-accent': 'light-dark(#FFFFFF, #16102F)',
    '--color-on-success': 'light-dark(#FFFFFF, #022C1C)',
    '--color-on-error': 'light-dark(#FFFFFF, #2A0A0A)',
    '--color-on-warning': '#2A1F00',
    '--color-icon-accent': 'var(--color-accent)',
    '--color-icon-primary': 'light-dark(#0C1013, #F5F8FD)',
    '--color-icon-secondary': 'light-dark(#626668, #9FB0C8)',
    '--color-icon-disabled': 'light-dark(#9A9EA0, #62728C)',
    '--color-success': 'light-dark(#0E9F6E, #34D399)',
    '--color-error': 'light-dark(#C0243C, #FF8A8A)',
    '--color-warning': 'light-dark(#9A6B00, #FACC57)',
    '--color-success-muted': 'light-dark(#DDF7EA, #34D39929)',
    '--color-error-muted': 'light-dark(#FBE0E2, #FF6B6B29)',
    '--color-warning-muted': 'light-dark(#FBEECB, #F5C63329)',
    '--color-border': 'light-dark(#E9E9E9, #24374F)',
    '--color-border-emphasized': 'light-dark(#DCDCDC, #375070)',
    '--color-skeleton': 'light-dark(#E7E7E7, #223449)',
    '--color-shadow': 'light-dark(#0C10131F, #00040C66)',
    '--color-tint-hover': 'light-dark(black, white)',
    '--color-background-red': 'light-dark(#FBE0E2, #FF6B6B29)',
    '--color-border-red': 'light-dark(#F0C2C6, #FF7A7A)',
    '--color-icon-red': 'light-dark(#C0243C, #FF8A8A)',
    '--color-text-red': 'light-dark(#A31D31, #FFB3B3)',
    '--color-background-orange': 'light-dark(#FCE7D3, #FB923C29)',
    '--color-border-orange': 'light-dark(#F3CBA8, #F59E52)',
    '--color-icon-orange': 'light-dark(#B45309, #FBB165)',
    '--color-text-orange': 'light-dark(#9A4A08, #FDD0A8)',
    '--color-background-yellow': 'light-dark(#FBEECB, #F5C63329)',
    '--color-border-yellow': 'light-dark(#EDD891, #D8AB2E)',
    '--color-icon-yellow': 'light-dark(#9A6B00, #F5C633)',
    '--color-text-yellow': 'light-dark(#7A5500, #FADA6E)',
    '--color-background-green': 'light-dark(#DDF7EA, #34D39929)',
    '--color-border-green': 'light-dark(#A7DCC2, #4FBE8B)',
    '--color-icon-green': 'light-dark(#0E7A4F, #7FE0B4)',
    '--color-text-green': 'light-dark(#0E7A4F, #7FE0B4)',
    '--color-background-teal': 'light-dark(#CBEDE6, #5FC4B429)',
    '--color-border-teal': 'light-dark(#A4DED2, #4FA99A)',
    '--color-icon-teal': 'light-dark(#0E7A6B, #6FD0BF)',
    '--color-text-teal': 'light-dark(#0A5C50, #9BE7D8)',
    '--color-background-cyan': 'light-dark(#CBEAF2, #55B7CE29)',
    '--color-border-cyan': 'light-dark(#A2DAE8, #4C9DB2)',
    '--color-icon-cyan': 'light-dark(#0A6478, #6FC3D6)',
    '--color-text-cyan': 'light-dark(#08505F, #9DDDEE)',
    '--color-background-blue': 'light-dark(#DCE8FF, #16294A)',
    '--color-border-blue': 'light-dark(#B6CCEC, #5A86E0)',
    '--color-icon-blue': 'light-dark(#3B6FD4, #9CBEFF)',
    '--color-text-blue': 'light-dark(#1D4FD8, #C2D3FF)',
    '--color-background-purple': 'light-dark(#ECD9F5, #C77DFF29)',
    '--color-border-purple': 'light-dark(#DBBFEA, #B36BE6)',
    '--color-icon-purple': 'light-dark(#8B1A9E, #DA9BF5)',
    '--color-text-purple': 'light-dark(#71167F, #EAC1FF)',
    '--color-background-pink': 'light-dark(#FBD9E7, #F871A929)',
    '--color-border-pink': 'light-dark(#EFBBCE, #EC6FA0)',
    '--color-icon-pink': 'light-dark(#A31059, #F98CBB)',
    '--color-text-pink': 'light-dark(#87094A, #FFC0DA)',
    '--color-background-gray': 'light-dark(#F3F3F3, var(--color-neutral))',
    '--color-border-gray': 'light-dark(#E0E0E0, #2A3B52)',
    '--color-icon-gray': 'light-dark(#626668, #9FB0C8)',
    '--color-text-gray': 'light-dark(#3D4143, #E5E9F0)',
    '--color-background-inverted': 'light-dark(#0C1013, #F5F8FD)',
    '--color-track': 'light-dark(#E4E4E4, #223449)',
    '--radius-element': '16px',
    '--radius-container': '20px',
    '--radius-page': '24px',
    '--radius-chat': '20px',
    '--shadow-low': '0 1px 2px rgb(12 16 19 / 0.05), 0 4px 12px rgb(12 16 19 / 0.04)',
    '--shadow-med': '0 2px 4px rgb(12 16 19 / 0.06), 0 12px 30px rgb(12 16 19 / 0.07)',
    '--shadow-high': '0 4px 10px rgb(12 16 19 / 0.08), 0 24px 64px rgb(12 16 19 / 0.14)',
    '--shadow-inset-hover': 'inset 0px 0px 0px 2px #6557E84D',
    '--shadow-inset-selected': 'inset 0px 0px 0px 2px #6557E880',
    '--shadow-inset-success': 'inset 0px 0px 0px 2px #0E9F6E4D',
    '--shadow-inset-warning': 'inset 0px 0px 0px 2px #F5C6334D',
    '--shadow-inset-error': 'inset 0px 0px 0px 2px #C0243C4D',
  },
  components: {
    button: {
      base: {
        fontWeight: '600',
        '--button-press-scale': 'scale(0.98)',
      },
    },
    badge: {
      'variant:info': {
        backgroundColor: 'light-dark(#3B6FD4, #6D9CFE)',
        color: 'light-dark(#FFFFFF, #0C1B33)',
      },
      'variant:neutral': {
        backgroundColor: 'var(--color-success-muted)',
        color: 'var(--color-success)',
      },
      'variant:success': {
        backgroundColor: 'var(--color-success-muted)',
        color: 'var(--color-success)',
      },
      'variant:warning': {
        backgroundColor: '#F5C633',
        color: 'var(--color-on-warning)',
      },
      'variant:error': {
        backgroundColor: 'light-dark(#C0243C, #FF8A8A)',
        color: 'var(--color-on-error)',
      },
      'variant:green': {
        backgroundColor: 'var(--color-accent-muted)',
        color: 'var(--color-accent)',
      },
    },
    progressbar: {
      'variant:accent': {
        '--color-accent': 'light-dark(#3B6FD4, #6D9CFE)',
      },
      'variant:success': {
        '--color-success': 'light-dark(#0E9F6E, #34D399)',
      },
      'variant:warning': {
        '--color-warning': '#F5C633',
      },
      'variant:error': {
        '--color-error': 'light-dark(#C0243C, #FF8A8A)',
      },
    },
    card: {
      base: {
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'var(--color-border)',
        boxShadow: 'var(--shadow-low)',
      },
    },
  },
})
