// Application-owned, user-facing copy lives here. API-provided content is intentionally excluded.
export const strings = {
  shared: {
    portal: 'Portal',
    signIn: 'Sign in',
    createAccount: 'Create account',
    emailAddress: 'Email address',
    password: 'Password',
    firstName: 'First name',
    lastName: 'Last name',
    terms: 'Terms',
    termsOfService: 'Terms of service',
    privacyPolicy: 'Privacy policy',
    loading: 'Loading…',
    tryAgain: 'Try again',
    checkTheHighlightedFieldsAndTryAgain: 'Check the highlighted fields and try again.',
    enterAValidEmailAddress: 'Enter a valid email address.',
    enterYourPassword: 'Enter your password.',
    theEmailOrPasswordIsIncorrect: 'The email or password is incorrect.',
    youCompanyCom: 'you@company.com',
    overview: 'Overview',
    activity: 'Activity',
    team: 'Team',
    resources: 'Resources',
    settings: 'Settings',
    openNavigation: 'Open navigation',
    closeNavigation: 'Close navigation',
    viewAll: 'View all',
  },
  metadata: {
    layout: {
      title: 'Portal — the reusable portal starter',
      titleTemplate: '%s · Portal',
      description: 'A production-minded Next.js portal template with theming, authentication choices, realtime hooks, string catalogs, and reusable UI foundations.',
      template: 'portal template',
      nextjsStarter: 'Next.js starter',
      authenticatedPortal: 'authenticated portal',
      designSystem: 'design system',
      alt: 'Portal template preview',
    },
    loginPage: {
      description: 'Sign in to the Portal template workspace.',
    },
    signupPage: {
      description: 'Create an account in the Portal template.',
    },
    forgotPasswordPage: {
      resetPassword: 'Reset password',
    },
    privacyPage: {
      description: 'Template privacy policy guidance for Portal.',
    },
    termsPage: {
      description: 'Template terms of service guidance for Portal.',
    },
    apiBackendPathRoute: {
      forbidden: 'Forbidden',
      untrustedOrigin: 'This request did not originate from Portal.',
      unauthorized: 'Unauthorized',
      sessionExpired: 'Your session has expired. Sign in again.',
    },
    devSettingsPage: {
      developerSettings: 'Developer settings',
    },
  },
  marketing: {
    navigation: {
      capabilities: 'Capabilities',
      workflow: 'Workflow',
      foundations: 'Foundations',
      primary: 'Primary navigation',
      footer: 'Footer navigation',
    },
    eyebrow: 'A serious head start',
    headlineStart: 'Your next portal,',
    headlineEnd: 'already in motion.',
    intro: 'Portal packages the expensive, repetitive foundation of a modern web product so each new project can start with its own domain—not another week of setup.',
    exploreTemplate: 'Explore the template',
    openDemo: 'Open portal demo',
    demoNote: 'The demo runs without credentials. Firebase and custom auth are opt-in.',
    preview: {
      workspace: 'Acme workspace',
      greeting: 'Good morning, Morgan',
      summary: 'Here is what changed across your workspace.',
      members: 'Members',
      activeItems: 'Active items',
      completion: 'Completion',
      latestActivity: 'Latest activity',
      designReview: 'Design review approved',
      accessUpdated: 'Workspace access updated',
      guidePublished: 'Onboarding guide published',
    },
    capabilityEyebrow: 'Choose what the product needs',
    capabilityTitle: 'A template with decisions made visible.',
    capabilityDescription: 'Every major capability is isolated, documented, and safe to keep, adapt, or remove before domain work begins.',
    capabilities: {
      identityTitle: 'Identity on your terms',
      identityDescription: 'Start with a no-auth demo, enable the Firebase adapter, or replace the boundary with your own provider.',
      realtimeTitle: 'Realtime when it earns its place',
      realtimeDescription: 'Socket.IO transport and validated event envelopes are available without forcing every product to keep a live connection.',
      systemTitle: 'A UI system that scales',
      systemDescription: 'Semantic tokens, light and dark themes, reusable states, responsive shell patterns, and a component workbench are included.',
      copyTitle: 'Copy has a home',
      copyDescription: 'User-facing strings live in a typed catalog, with lint rules that stop stray interface copy from spreading through components.',
      apiTitle: 'A safe backend boundary',
      apiDescription: 'Server-only environment access, encrypted sessions, same-origin request proxying, and typed service interfaces are ready to adapt.',
      operationsTitle: 'Operational readiness',
      operationsDescription: 'Metadata, robots, sitemap, error and loading states, environment examples, and launch checklists ship with the foundation.',
    },
    workflowEyebrow: 'From template to product',
    workflowTitle: 'Keep the head start. Replace the assumptions.',
    workflowDescription: 'The project checklist walks an AI or developer through product decisions before implementation changes the architecture.',
    workflowSteps: {
      decide: 'Decide',
      decideDescription: 'Choose auth, persistence, API, realtime, notifications, analytics, uploads, email, and deployment.',
      rename: 'Make it yours',
      renameDescription: 'Replace the Portal brand, theme tokens, metadata, legal copy, and example data from their documented sources of truth.',
      model: 'Model the domain',
      modelDescription: 'Swap the example workspace models for the product’s own language, services, routes, and permissions.',
      verify: 'Verify',
      verifyDescription: 'Run strings enforcement, lint, type checks, production build, accessibility review, and the launch checklist.',
    },
    foundationsEyebrow: 'Batteries included, assumptions optional',
    foundationsTitle: 'Built to be deleted from.',
    foundationsDescription: 'The best template is not the one with the most code. It is the one that makes every piece easy to understand, keep, replace, or remove.',
    foundationItems: {
      routes: 'App Router route groups, layouts, metadata, loading, and error boundaries',
      responsive: 'Responsive marketing, auth, and authenticated shell patterns',
      forms: 'Reusable fields, actions, validation states, notices, and confirmation flows',
      data: 'TanStack Query provider and browser/server API clients',
      theme: 'Astryx semantic theme source with generated artifacts',
      docs: 'AI-ready project creation checklist and decision guides',
    },
    finalEyebrow: 'Start with the part that usually comes later',
    finalTitle: 'A coherent product surface on day one.',
    finalDescription: 'Clone Portal, answer the setup checklist, and spend the first sprint on the product’s differentiator.',
    start: 'Start with Portal',
    copyright: 'Reusable portal foundation. Replace this copy before launch.',
  },
  auth: {
    actions: {
      acceptTerms: 'Accept the Terms and Privacy Policy to continue.',
      firstName: 'Enter your first name.',
      lastName: 'Enter your last name.',
      passwordsMatch: 'Passwords do not match.',
      passwordLength: 'Use at least eight characters.',
      welcomeBack: 'Welcome back.',
      workspaceReady: 'Your workspace is ready.',
      resetSent: 'If an account exists for that email, a reset link is on its way.',
      firebaseRequired: 'Firebase authentication is not configured. Review docs/AUTHENTICATION.md.',
      customRequired: 'Connect the custom auth adapter before enabling custom authentication.',
      genericError: 'Authentication could not be completed. Please try again.',
    },
    shell: {
      eyebrow: 'A complete product shell',
      title: 'Identity is one decision, not the whole architecture.',
      description: 'Use the included flow as a polished demo, connect Firebase, or keep the UI and replace the auth boundary.',
      itemOne: 'Accessible sign-in, sign-up, and recovery states',
      itemTwo: 'Encrypted, HTTP-only session support',
      itemThree: 'Clear integration seams for custom providers',
      footnote: 'Portal template · authentication is configurable',
      back: 'Back to Portal',
    },
    login: {
      eyebrow: 'Welcome back',
      title: 'Sign in to your workspace',
      description: 'Use any valid-looking credentials in demo mode.',
      forgot: 'Forgot password?',
      new: 'New to Portal?',
      create: 'Create an account',
    },
    signup: {
      eyebrow: 'Create your workspace',
      title: 'Start with a complete portal',
      description: 'The demo validates the full flow without storing an account.',
      workEmail: 'Work email',
      confirmPassword: 'Confirm password',
      passwordHint: 'At least 8 characters',
      agree: 'I agree to the',
      and: 'and',
      existing: 'Already have an account?',
    },
    reset: {
      eyebrow: 'Password help',
      title: 'Reset your password',
      description: 'We will send a secure reset link when a provider is connected.',
      send: 'Send reset link',
      remembered: 'Remembered it?',
      back: 'Back to sign in',
    },
    firebase: {
      accountExists: 'An account already exists for this email address.',
      failed: 'Authentication could not be completed. Please try again.',
      emailDisabled: 'Email and password sign-in is not enabled.',
      noAccount: 'No account was found for this email address.',
      disabled: 'This account has been disabled. Contact support for help.',
      tooMany: 'Too many attempts. Please wait a moment and try again.',
      weakPassword: 'Use a stronger password with at least eight characters.',
    },
    logout: {
      signOut: 'Sign out',
    },
  },
  portal: {
    shell: {
      navigation: 'Portal navigation',
      workspace: 'Workspace',
      templateMode: 'Template mode',
      demoUser: 'Morgan Lee',
      demoEmail: 'morgan@example.com',
      demoInitials: 'ML',
      account: 'Account and workspace settings',
    },
    dashboard: {
      eyebrow: 'Friday, July 24',
      title: 'Good morning, Morgan',
      description: 'A neutral example dashboard, ready to be replaced with your product domain.',
      launchTitle: 'Project launch checklist',
      launchDescription: 'Use the docs before replacing examples so infrastructure decisions stay explicit.',
      launchAction: 'Open setup guide',
      docsPath: 'docs/',
      metricMembers: 'Workspace members',
      metricActive: 'Active items',
      metricCompletion: 'Completion rate',
      metricResponse: 'Avg. response',
      metricMembersDetail: 'Across 3 access levels',
      metricActiveDetail: '4 need review',
      metricCompletionDetail: 'Up 12% this month',
      metricResponseDetail: 'During working hours',
      recentActivity: 'Recent activity',
      recentActivityDescription: 'Example events from a generic workspace.',
      quickActions: 'Quick actions',
      inviteMember: 'Invite a member',
      addResource: 'Add a resource',
      reviewSettings: 'Review settings',
      architecture: 'Template architecture',
      architectureDescription: 'Marketing, auth, portal, services, theme, content, and documentation are deliberately separated.',
    },
    activity: {
      eyebrow: 'Workspace history',
      title: 'Activity',
      description: 'A feed example for audit events, collaboration updates, and system notifications.',
      allActivity: 'All activity',
    },
    team: {
      eyebrow: 'People and access',
      title: 'Team',
      description: 'Example roles demonstrate how a real product can surface membership and permissions.',
      invite: 'Invite member',
      role: 'Role',
      status: 'Status',
      lastActive: 'Last active',
    },
    resources: {
      eyebrow: 'Shared knowledge',
      title: 'Resources',
      description: 'A neutral list pattern for documents, links, files, records, or any other domain object.',
      add: 'Add resource',
      owner: 'Owner',
      updated: 'Updated',
      type: 'Type',
    },
    settings: {
      eyebrow: 'Template configuration',
      title: 'Settings',
      description: 'The example reflects current environment choices without exposing secrets.',
      capability: 'Capability',
      current: 'Current mode',
      nextStep: 'Next step',
      authentication: 'Authentication',
      realtime: 'Realtime',
      api: 'Backend API',
      theme: 'Theme',
      strings: 'String catalog',
      reviewAuth: 'Review AUTHENTICATION.md before enabling a provider.',
      reviewRealtime: 'Review REALTIME.md before enabling Socket.IO.',
      reviewApi: 'Replace example models before connecting product endpoints.',
      reviewTheme: 'Edit portalDesignSystem.ts, then rebuild generated artifacts.',
      reviewStrings: 'Keep interface copy in src/content/strings.ts.',
    },
  },
  demo: {
    activities: {
      approvedTitle: 'Design review approved',
      approvedDetail: 'Alex moved the launch review into the approved state.',
      accessTitle: 'Workspace access updated',
      accessDetail: 'Sam changed Jordan’s role from Viewer to Member.',
      guideTitle: 'Onboarding guide published',
      guideDetail: 'Morgan added a new guide to Shared resources.',
      automationTitle: 'Weekly digest completed',
      automationDetail: 'The example automation processed 18 workspace events.',
    },
    members: {
      morgan: 'Morgan Lee',
      alex: 'Alex Rivera',
      jordan: 'Jordan Chen',
      sam: 'Sam Patel',
      owner: 'Owner',
      admin: 'Admin',
      member: 'Member',
      viewer: 'Viewer',
      active: 'Active',
      invited: 'Invited',
      now: 'Now',
      yesterday: 'Yesterday',
      twoDaysAgo: '2 days ago',
      pending: 'Pending',
    },
    resources: {
      onboarding: 'Workspace onboarding',
      launch: 'Launch readiness checklist',
      design: 'Design system reference',
      api: 'API integration map',
      guide: 'Guide',
      checklist: 'Checklist',
      reference: 'Reference',
      diagram: 'Diagram',
    },
  },
  devSettings: {
    eyebrow: 'Local-only workbench',
    title: 'Developer settings',
    description: 'A compact inventory of the template foundation. Extend this route with product-specific component states as the domain grows.',
    versions: 'Runtime versions',
    tokens: 'Semantic tokens',
    components: 'Reusable primitives',
    componentsDescription: 'Buttons, cards, fields, loading, errors, empty states, confirmations, theme controls, and the responsive shell are ready to compose.',
    colors: 'Color roles',
    spacing: 'Spacing and shape',
    copy: 'All visible copy is catalog-backed and checked during lint.',
    onlyDevelopment: 'This route is available only in development.',
  },
  legal: {
    templateNotice: 'Template notice',
    templateDescription: 'This is placeholder legal content, not legal advice. Replace it with reviewed product-specific terms before launch.',
    privacyIntro: 'Describe what data the product collects, why it is processed, how long it is retained, which vendors receive it, and how users exercise their rights.',
    termsIntro: 'Describe account responsibilities, acceptable use, payment terms, service availability, intellectual property, termination, warranties, and liability.',
    checklistTitle: 'Required replacement checklist',
    itemIdentity: 'Identify the legal entity and contact details.',
    itemData: 'Document real data flows and subprocessors.',
    itemRegion: 'Address every region where the product operates.',
    itemReview: 'Obtain qualified legal review before publishing.',
    back: 'Back to home',
  },
  common: {
    errorState: {
      title: 'Something went wrong',
      description: 'The request could not be completed. Please try again.',
    },
    filterResults: {
      clear: 'Clear filters',
    },
    logo: {
      home: 'Portal home',
    },
    theme: {
      dark: 'Use dark theme',
      light: 'Use light theme',
    },
  },
} as const

export const formatStrings = {
  common: {
    resultCount: (count: number, singularLabel: string) => `${count} ${count === 1 ? singularLabel : `${singularLabel}s`}`,
  },
  services: {
    apiReturnedStatus: (status: number) => `The API returned status ${status}.`,
    browserRequestReturnedStatus: (status: number) => `The request returned status ${status}.`,
  },
} as const
